onlyflans/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth import views as auth_views
#from webApp.views import inicio, acerca, bienvenido, registro
from webApp import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', views.inicio, name='inicio'),
    path('acerca', views.acerca, name='acerca'),
    path('bienvenido', views.bienvenido, name='bienvenido'),
    path('registro', views.registro, name='registro'),
    path('contacto', views.contacto, name='contacto'),
    path('exito', views.exito, name='exito'),
    #path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]

webApp/models.py
from django.db import models
import uuid

# Create your models (class)(tabla) here.
class Flan(models.Model):
    #nombre_atributo = tipo_de_dato
    flan_uuid = models.UUIDField()
    name = models.CharField(max_length=64)  #varchar
    descripcion = models.TextField()
    image_url = models.URLField()
    url = models.CharField(max_length=64)
    slug= models.SlugField()
    id_private= models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"objeto Flan: ({self.id}) - {self.name}"
    
class ContactForm(models.Model):
    contact_form_uuid = models.UUIDField(default=uuid.uuid4,editable=False) #con valor por defecto uuid.uuid4, no editable
    customer_email = models.EmailField()
    customer_name = models.CharField(max_length=64) 
    message = models.TextField()
    
    def __str__(self) -> str:
        return f"Contact Form: ({self.id}) - {self.customer_email}"
        
        
        

webApp/forms.py
from django import forms
  
class ContacFormForm(forms.Form):
    customer_email = forms.EmailField(label="Correo")
    customer_name = forms.CharField(max_length=64, label="Nombre") 
    message = forms.CharField(label="Mensaje")
    
    

webApp/views.py
from django.shortcuts import render,HttpResponse, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from .models import Flan, ContactForm
from . forms import ContacFormForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

# Create your views here.
def inicio(request):
    #select * from flan;
    flanes = Flan.objects.all()
    
    #select * from WHERE is_private=False;
    flanes = Flan.objects.filter(id_private=False)
    
    contex = {
       "lista_flanes": flanes
    }
    return render (request, "index.html", contex)

def acerca(request):
    return render (request, "acerca.html",{})

@login_required
def bienvenido(request):
    #request.session['nombre']="Juan"
    flanes= Flan.objects.filter(id_private=True)
    contex = {
       "lista_flanes": flanes
    }
    return render (request, "bienvenido.html",contex)

def registro(request):
    if request.method =="POST":
        username = request.POST("username")
        email = request.POST("email")
        password = request.POST["password"]
        
        user = User.objects.create_user(username, email, password)  
        user.save()#inserta o actualiza
        
    return redirect ("/login")

def contacto(request):
    if request.method =="POST":
        form = ContacFormForm(request.POST)
        print(form)
        if form.is_valid():
            #aplicar logica
            form2 = ContactForm.objects.create(**form.cleaned_data)
            return redirect('/exito')
    else:
        form = ContacFormForm()   
        context ={
            "form": form
        }    
    return render (request, "contacto.html",context)

def exito(request):
    return render (request, "exito.html",{})

"""
def login(request):
    #get -> mostrar el html
    if request.metodo == "GET":
        return render (request,"login2.html")
    
    #post -> capturar datos desde el html
    if request.method =="POST":
        email = request.POST("email")
        password = request.POST["password"]
        #crear un objeto y asignar los valores
        #crear el registro en la base de datos
            #objeto.save()
            
        #uso de sesion
        
        request.session ["email"] = email
        
        return redirect("/")
"""    

webApp/templates/acerca.html
{% extends "base.html" %}

{% block 'content' %}
 <div class="container"> 
        <h1>Nuestra Historia...</h1>
        <br>
        <h2>OnlyFlans es una empresa enfocada en el mundo de la pastelería y los postres, 
            en especial en la venta de flan(de ahí su nombre), 
            nace en 2021 en santiago de chile como una empresa familiar
            que pretende entregar productos de calidad a su clientela, 
            estando ubicada en providencia, a pasos del metro Parque Bustamante.</h2>
</div>
{% endblock%}

    

webApp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bienvenidos a onlyflans</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}}" >
    <script> </script>
    
</head>
<body>
    {% block 'navbar' %}
    {% include "navbar.html" %}
    {% endblock  %}

    {% block 'header' %}
    {% include "header.html" %}
    {% endblock  %}

    {% block 'content' %}
        <div class="container">
            CONTAINER
        </div>
    {% endblock  %}
    
    {% block 'footer' %}
    {% include "footer.html" %}
    {% endblock%} 
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

webApp/templates/bienvenido.html
{% extends 'base.html' %}

{% block 'content' %}
<div class="container">
  <br>
  <h2>Bienvenido {{user.get_username}}</h2>
  <h3>Nuestros Flanes especiales para tu gusto...</h3>
  <br>
  {% block 'card' %}
  {% include 'card.html' %}
  {% endblock %}
  
</div>
{% endblock %}

webApp/templates/card.html
<div class="row mt-4 mb-4">
  {% for flan in lista_flanes %}
  <div class="col-6 col-md-4" style="width:25rem; ">
    <div class="card mb-5" style="">
      <img src="{{ flan.image_url }}" class="card-img-top" alt="..." width="18rem" height="250px">
      <div class="card-body">
        <h5 class="card-title">
          {{ flan.name }}
        </h5>
        <p class="card-text">
          {{ flan.description }}
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

webApp/templates/contacto.html
{% extends "base.html" %}

{% block 'content' %}
 <div class="container"> 
        
    <h1> Contáctenos<br></h1>
        <form action="{% url "contacto" %}" method="post">
                {% csrf_token %}        
                        
                <div>
                        <label class="form-label" for="id_customer_email">Correo:</label>
                        <input class="form-control" type="email" name="customer_email" maxlength="320" required="" id="id_customer_email">
                </div>
                <div>
                        <label class="form-label" for="id_customer_name">Nombre:</label>
                        <input class="form-control" type="text" name="customer_name" maxlength="64" required="" id="id_customer_name">
                </div>
                <div>
                        <label class="form-label" for="id_message">Mensaje:</label>
                        <input class="form-control" type="text" name="message" required="" id="id_message">
                </div>
                <button type="submit" class="btn btn-primary">Enviar Formulario</button>            
        </form>

</div>
{% endblock%}

webApp/templates/exito.html
{% extends "base.html" %}

{% block 'content' %}
 <div class="container text-center"> 
        <h1>Gracias por contactarte con OnlyFlans,</h1>
        <h1>te responderemos en breve</h1>
        <a href="/" class="btn btn-primary" role="button">Volver al inicio</a>
</div>
{% endblock%}

webApp/templates/footer.html
<footer class=" py-3 my-4 border-top" >

    <ul class="nav col-med-4 justify-content-end ">
        <li class="nav-item"><a href="{% url 'inicio' %}" class="nav-link px-2 text-body-secondary">Inicio</a></li>
        <li class="nav-item"><a href="{% url 'acerca' %}" class="nav-link px-2 text-body-secondary">Acerca</a></li>
        <li class="nav-item"><a href="{% url 'bienvenido' %}" class="nav-link px-2 text-body-secondary">Bienvenido</a></li>    
    </ul>
    <p class="text-center text-body-secondary" > Creado por Flavia Cayun y Juan Torres para Desafio Latam 2024</p>
</footer>

webApp/templates/header.html
{% load static %}
<header>
    <div class="container col-4 offset-5" >
        <img src="{% static 'img/OnlyFlans.png' %}" alt="Onlyflans" class="img-fluid" width="350px" />
    </div>
</header>
</html>

webApp/templates/index.html
{% extends 'base.html' %}

{% block 'content' %}
<div class="container">
    
    <h1>Nuestros Productos</h1>
    <br>
    {% block 'card' %}
    {% include 'card.html' %}
    {% endblock %}
    
</div>
{% endblock %}

webApp/templates/navbar.html
{% load static %}
 <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"> 
        <img src="{% static 'img/OnlyFlans.png' %}" alt="OnlyFlans" width="80"/>
      </a>  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'acerca' %}>Acerca</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="bienvenido">Bienvenido</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contacto">Contacto</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.is_authenticated %}
              {{ user.get_username}}
              {% else %}
              Login
              {% endif %}
            </a>
            <ul class="dropdown-menu">
              {% if user.is_authenticated %}
                  <li>
                      <form action="{% url 'logout'%}" method="post" class="d-flex" role="search">
                          {% csrf_token %}
                          <button class="btn btn-outline-success" type="submit">Cerrar sesión</button>
                      </form>
                  </li>
              {% else %}
                  <li><a href="{% url 'login'%}">Iniciar sesión</a></li>
              {% endif %}
          </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

webApp/templates/registro.html
{% extends "base.html" %}

{% block 'content' %}
<div class='container'>
    <form>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1">
        </div>

        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>
{% endblock %}